apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myweb
  namespace: argocd
spec:
  description: 'Argocd Test'
  destinations:
  - namespace: mynginx
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'

